name: Static Analysis
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    name: PHPStan
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Composer Install
        run: composer install --dev
      - name: Run phpstan
        run: ./vendor/bin/phpstan analyse src tests -l 5
